[env:native]
platform = native
build_flags =
	-g
	-std=c++17
	-Wno-comment
	-fno-pretty-templates
debug_build_flags = -O0 -ggdb3 -g3 -no-pie
	-Wno-comment
	-fno-pretty-templates
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git
	OneBit    = https://github.com/InternetOfPins/OneBit.git
	OnePin    = https://github.com/InternetOfPins/OnePin.git
	OneBus    = https://github.com/InternetOfPins/OneBus.git
	OneChip   = https://github.com/InternetOfPins/OneChip.git
	OneData   = https://github.com/InternetOfPins/OneData.git
	OneOutput = https://github.com/InternetOfPins/OneOutput.git
	OneItem   = https://github.com/InternetOfPins/OneItem.git
	OneParse  = https://github.com/InternetOfPins/OneParse.git
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git
