name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples/arduino_[serial]-static-[serial]/arduino_[serial]-static-[serial]/arduino_[serial]-static-[serial].ino]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        # wget https://github.com/xxxajk/spi4teensy3/archive/master.zip -O /tmp/spi4teensy3.zip
        # unzip /tmp/spi4teensy3.zip -d /tmp

    - name: Run PlatformIO
      run: platformio ci --board=uno
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
