[env:native]
platform = native
build_flags =
	-g
	-std=c++17
	-Wno-comment
	-fno-pretty-templates
debug_build_flags = -O0 -ggdb3 -g3 -no-pie
	-Wno-comment
	-fno-pretty-templates
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git#a7e32cb11fefa80e99174e8ccb9b571bac62f6e1
	OneBit    = https://github.com/InternetOfPins/OneBit.git#c57022267bf56fc0ffeb8c5aa7adc1e52eaf7ff1
	OnePin    = https://github.com/InternetOfPins/OnePin.git#67acf0658afc8699b0dd8c4591890b66ef2ce739
	OneBus    = https://github.com/InternetOfPins/OneBus.git#701171a9bdebdccb25f715f610e715b79b15c2e5
	OneChip   = https://github.com/InternetOfPins/OneChip.git#7bb584a12e261afe4e5f87c7f4e655ca998605e6
	OneData   = https://github.com/InternetOfPins/OneData.git#2b11f2c278779321e4fd3e0e49b5434cd20b7944
	OneOutput = https://github.com/InternetOfPins/OneOutput.git#b67fd00146c0e4963d6054eb7629645764b91655
	OneItem   = https://github.com/InternetOfPins/OneItem.git#c8bb35d6f75307fc783dfd62680e2e771d1ecb06
	OneParse  = https://github.com/InternetOfPins/OneParse.git#d5529fe36b53eec78c18c4b3e6b560312d7491ce
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git#704b7fa44119286bdf0d8e95d0e50ee967d7f248
